Исправил, дз 2
KapustaKosta/MIPT-Java-lessons pull request #5
Opened 2023-10-09 13:12 UTC by KapustaKosta

2023-10-15 22:54 UTC, ASemenovng requested changes

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/shape/Shape.java
> +sealed public class Shape permits Ball, Cylinder, Pyramid {
Лучше public sealed - в таком порядке, обычно модификатор доступа идет первым

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/pet/Pet.java
> +  public enum FeedType {
1. Тип корма лучше вынести отдельно, он не привязан ведь непосредственно к Pet
2. Внутри enum элементы принято называть капсом

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/pet/Parrot.java
> +  {
скобку { перенеси наверх
пишут
```java
ClassName {
  // smth
}
```
но не так
```java
ClassName
{
  // smth
}
```
Аналогично с методами
Это просмотри и по другим местам

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/pet/Dog.java
> +  public enum Breed
Вынеси Breed, не нужно писать его внутри Dog. Как минимум ты пишешь его дважды - тут и в Cat. А если появятся еще животные, у которых будет такое поле, тебе придется у каждого из них написать его или обращаться к классу Breed внутри Dog еру, что не очень логично

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/Point.java
> +  public Point scale(double x) {
Тут входящий параметр назвать не x, а как-то иначе, чтобы не путалось с полем класса

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/IntHolder.java
> +  private int num;
между объявлениями класса, полей, методов и тд делай пробелы, чтобы код нормально читался

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/IntHolder.java
> +  public void modulo(IntHolder intHolder)
Лучше не называть методы modulo и в таком духе - это транслит. Назови remainder или что нибудь такое

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/IntHolder.java
> +  public boolean equals(Object o)
А почему не проверяешь на равенство ссылок? Это ведь быстрее и если они равны, то не придется делать каст и проверять равенство полей, а можно сразу вернуть true

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/IntHolder.java
> +    return this.num;
Забавно) Но с такой реализацией есть одна проблема: к хэш функциям обычно есть требование, что если входы различаются незначительно, то выходы должны отличаться уже сильно, То есть хэш должен +- равномерно распределяться независимо от того, какие объекты у тебя - похожие или разные. Почему это может быть нужно: к примеру при работе с хэш-мапой (если знаешь, что это - если нет - это словарь, в котором индекс элемента зависит от его хэша) в твоем случае индекс в мапе = хэш = значение, которое лежит внутри. Это плохо по двум параметрам:
1. Пусть у меня мапа на 100 элементов, и есть холдеры с 80 по 100 - тогда все они лягут на номера с 80 по сотый, хотя зачастую лучше, если бы они лежали +- равномерно
2. Пусть у тебя мапа на 10 элементов, тогда индекс - это хэш % длина мапы (в нашем случае 10). Тогда холдеры со значениями 5, 15, 25 и тд лягут в одно место - это не очень хорошо

Ну то есть глобально если у тебя элементы, для которых ты считаешь хэш как-то сконцентрированы вокруг какого-то значения, хэш должен это исправлять и хэши уже не должны так концентрироваться, а бить равномерно распределены по возможному диапазону

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/Contact.java
> +  private static final String DEFAULT_EMAIL = "my-email@gmail.com";
аналогично пробелы

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/Contact.java
> +    if(!emailValid)
Тут переменная emailValid выглядит лишней, можно просто в if(...) добавить условие
Заведение такой переменной имеет смысл, если твое условие сложное и выглядит громоздко, или если оно составное. А тут у тебя всего одна проверка

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/Car.java
> +  public Car(Bulder bulder)
Этот конструктор лучше сделать приватным, он ведь тебе нужен только внутри билдера, зачем давать доступ к нему наружу?
В целом можно придерживаться принципа, что при разработке твои классы нужно делать максимально "закрытыми" - это касается и полей, и методов и возможности переопределения методов и так далее. А доступ наружу давать только там, где это реально нужно

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/Car.java
> +  private static class Engine {
Класс Engine не очень логично делать статиком, все таки у тебя на каждую машину свой двигатель и двигатель в отвязке от машины тебе вряд ли пригодится. Тут проблема возникает внутри билдера, его то как раз стоит объявить статиком. Но тогда ты не можешь внутри создать объект Engine и присвоить его в нужное поле. Но вот что ты можешь сделать:
вместо строки private Engine engine; внутри билдера объяви строку private int fuelConsumption; А объект Engine создавай не в билдере, а внутри конструктора, тогда проблем со статик контекстом не будет

2023-10-15 22:54 UTC, ASemenovng commented on lesson-2/src/Main.java
> +  public static int partition(int l, int r)
А зачем тебе partition и Pair тут?

2023-10-16 12:59 UTC, KapustaKosta commented on lesson-2/src/Contact.java
> +    if(!emailValid)
Я завёл переменную emailValid, чтобы в дальнейшем, при добавлении новых условий валидности, не выносить всё в новую булеву переменную

2023-10-16 13:01 UTC, KapustaKosta commented on lesson-2/src/pet/Dog.java
> +  public enum Breed
Я пишу его дважды потому что у собак и кошек разные породы)

2023-10-21 19:59 UTC, closed without merging